"""empty message

Revision ID: 16830dfca9a8
Revises: 28226d3e028f
Create Date: 2023-07-20 21:49:37.260268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16830dfca9a8'
down_revision = '28226d3e028f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('con_req')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('con_req', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
