"""empty message

Revision ID: 28226d3e028f
Revises: 3c80b4891d51
Create Date: 2023-07-20 21:37:23.058828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28226d3e028f'
down_revision = '3c80b4891d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_date_time', sa.String(), nullable=True))
        batch_op.drop_column('app_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_time', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('app_date_time')

    # ### end Alembic commands ###
