"""empty message

Revision ID: 3c80b4891d51
Revises: 
Create Date: 2023-07-20 19:09:04.899187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c80b4891d51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('service_price', sa.String(), nullable=True),
    sa.Column('service_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stylists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stylist_name', sa.String(), nullable=True),
    sa.Column('stylist_info', sa.String(), nullable=True),
    sa.Column('stylist_img', sa.String(), nullable=True),
    sa.Column('services_provided', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('app_time', sa.String(), nullable=True),
    sa.Column('con_req', sa.Boolean(), nullable=True),
    sa.Column('stylist_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_appointments_service_id_services')),
    sa.ForeignKeyConstraint(['stylist_id'], ['stylists.id'], name=op.f('fk_appointments_stylist_id_stylists')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.drop_table('stylists')
    op.drop_table('services')
    # ### end Alembic commands ###
