"""empty message

Revision ID: b5bff9c043ce
Revises: 33b3907a8a8e
Create Date: 2023-07-19 11:46:51.978677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bff9c043ce'
down_revision = '33b3907a8a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stylists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services_provided', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stylists', schema=None) as batch_op:
        batch_op.drop_column('services_provided')

    # ### end Alembic commands ###
